Big rewrite and consul integration
UCCNetsoc/fail2rest pull request #5
Opened 2019-10-03 18:37 UTC by OisinA

2019-10-03 18:53 UTC, Strum355 requested changes

2019-10-03 18:53 UTC, Strum355 commented on Dockerfile
> +FROM golang:latest
pls pin go version :)

2019-10-03 18:53 UTC, Strum355 commented on main.go
> +	log.InitSimpleLogger(&log.Config{})
pls have this use JSON logger if in production :) recommend spf13/viper for loading and using config. see windlass codebase for example

2019-10-03 18:53 UTC, Strum355 commented on main.go
> +	port := "8080"
this port can be an spf13/viper setting :)

2019-10-07 13:42 UTC, Strum355 requested changes
:)

2019-10-07 13:42 UTC, Strum355 commented on api/jail.go
> +	}
Do we wanna use errHandle here?

2019-10-07 13:42 UTC, Strum355 commented on config/defaults.go
> +	viper.SetDefault("fail2rest.token-location", "fail2rest-token")
https://github.com/UCCNetworkingSociety/Windlass-worker/blob/master/app/config/defaults.go#L11-L30
See here for sample config style.

2019-10-07 13:42 UTC, Strum355 commented on config/defaults.go
> +	viper.SetDefault("fail2rest.token-location", "fail2rest-token")
`viper.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))` dont forget this to translate `ENV_LIKE_THIS` to `env.like.this`

2019-10-08 11:19 UTC, Strum355 requested changes

2019-10-08 11:19 UTC, Strum355 commented on api/api.go
> +	r.Use(a.authMiddleware)
im wondering do we want auth for the ping endpoint?

2019-10-08 11:19 UTC, Strum355 commented on main.go
> +	api := api.API{Fail2Conn: conn, Secret: consul.Secret}
do we need to pass the secret down if its in the viper settings?

2019-10-08 11:19 UTC, Strum355 commented on services/consul.go
> +		c.Secret = string(kv.Value)
id say assign the secret to `viper.Set("fail2rest.secret")` *or* do what youre doing here and delete the config default

2019-10-08 18:39 UTC, ArthanJans requested changes
You forgot to add an unban endpoint

2019-10-08 19:57 UTC, Strum355 approved these changes

2019-10-08 19:58 UTC, merged